import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { GoLocation } from "react-icons/go";
import { BsHandIndexThumb } from "react-icons/bs";
import { AiOutlineSafety } from "react-icons/ai";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";
import mapboxgl from "mapbox-gl";
import * as turf from "@turf/turf";
import MapSearchBox from "@/Components/MapSearchBox";
import Slider from "../Components/Slider";
import Vehicles from "@/Models/Vehicles";
import mongoose from "mongoose";
import { useMyContext } from "@/Context/userInfo/UserInfoContext";

const cityArr = ["Surat", "Ahemdabad"];
const reqArr = ["Shifting", "Cureir"];

mapboxgl.accessToken =
  "pk.eyJ1IjoiaHJwaXBhbGl5YSIsImEiOiJjbGxhcHc4bGgxdDA1M2Rta2trMWpzOGIwIn0.f7dxbVAqITPMkxSho7mNLQ";

export default function Home({ vehicles }) {
  const {
    city,
    setCity,
    pAddress,
    setpAddress,
    dAddress,
    setdAddress,
    requirement,
    setRequierment,
    distance,
    setDistance,
    pcoordinates,
    setpCoordinates,
    dcoordinates,
    setdCoordinates,
  } = useMyContext();

  const pAddressHandler = ({ label, coordinates }) => {
    setpAddress(label);
    setpCoordinates(coordinates);
  };
  const dAddressHandler = ({ label, coordinates }) => {
    setdAddress(label);
    setdCoordinates(coordinates);
  };

  const calculateDistance = () => {
    if (pcoordinates.length !== 2 || dcoordinates.length !== 2) {
      alert(
        "Please enter valid coordinates for both Picukup Address and Drop Address."
      );
      return;
    }

    const startPoint = turf.point(pcoordinates);
    const endPoint = turf.point(dcoordinates);
    const options = { units: "kilometers" };
    const distanceInKilometers = turf.distance(startPoint, endPoint, options);

    const distanceInteger = parseInt(distanceInKilometers.toFixed(2));

    setDistance(distanceInteger);
    return distance;
  };
  return (
    <>
      <Head>
        <title>Hire the Carrier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Hero Section */}
      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-blue-950">
              Find Your Perfect Vehicle For Transport
            </h1>
            <p className="mb-8 leading-relaxed text-justify w-8/12">
              This website is user-friendly, built for visitors and registered
              users such that users willfeel very comfortable working on it,
              before booking a truck customers have to create a new account or
              they can simply log in to the system with an existing account,
              registered users have access to truck booking, profile updates,
              sending and viewing testimonials . <br />A manager is a superuser
              who can manage any information that can be added, edited, or
              removed fromthe system, he can view the registered users, complete
              booking transactions, queries and history in his dashboard.
            </p>
            <div className="flex justify-center">
              <button className="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">
                Learn More
              </button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <Image
              className="object-cover object-center rounded-3xl"
              width={700}
              height={200}
              alt="truck"
              src="/2.jpg"
            />
          </div>
        </div>
      </section>
      {/* Search Section */}
      <section>
        <div className="flex flex-col lg:flex-row justify-center mt-5 mb-8">
          <div className=" lg:my-auto py-2 mx-auto">
            <div>
              <Autocomplete
                value={city}
                onChange={(event, newValue) => {
                  setCity(newValue);
                }}
                id="controllable-states-demo"
                options={cityArr}
                sx={{ width: 250 }}
                required={true}
                renderInput={(params) => <TextField {...params} label="City" />}
              />
            </div>
          </div>
          <div className="w-2/3 my-auto py-2 mx-auto lg:w-1/5">
            <MapSearchBox label="Pickup Address" onData={pAddressHandler} />
          </div>
          <div className="w-2/3 my-auto py-2 mx-auto lg:w-1/5">
            <MapSearchBox label="Drop Address" onData={dAddressHandler} />
          </div>

          <div className="lg:my-auto py-2 mx-auto">
            <div>
              <Autocomplete
                value={requirement}
                onChange={(event, newValue) => {
                  setRequierment(newValue);
                }}
                id="controllable-states-demo"
                options={reqArr}
                sx={{ width: 250 }}
                renderInput={(params) => (
                  <TextField {...params} label="Requirement" />
                )}
              />
            </div>
          </div>
          <div className="lg:my-auto mt-8 mx-auto">
            <button
              onClick={() => {
                if (calculateDistance()) {
                  Router.push({
                    pathname: "/Getestimate",
                  });
                }
              }}
              className="inline-flex  text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg"
            >
              Get Estimate
            </button>
          </div>
        </div>
        <div className=" text-sm text-center mt-5">
          {" "}
          NOTE: Base fare includes 10.0 km distance and 70 minutes of time
          Pricing may vary based on your locality.
        </div>
      </section>
      {/* About Section Here */}
      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            <Image
              className="object-cover object-center rounded-3xl"
              width={700}
              height={250}
              alt="truck"
              src="/3.jpg"
            />
          </div>
          <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-justify">
            <h6 className="font-semibold mb-2 text-blue-600">About Us</h6>
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-blue-950">
              We Provide The Best Vehical For You!
            </h1>
            <p className=" leading-relaxed">
              Just Hire a Vehicle Self Driven Carrier rental service originated
              in Surat, Gujarat and is successfully established itself as the
              leading Vehicle Rental service in Surat, Ahemdabad and Bharuch.
            </p>
            <p>
              With a Largest Fleet of all kinds of vehicles including TATA ACE,
              TATA 407, 3 WHEELER, 2 WHEELER. We have currently 1600+ members
              with 100 Plus vehicles.
            </p>
            <p>
              We offer 24/7 services. We specialise in the best customer
              service, Well maintained vehicles and Clean vehicles. All our
              vehicles are regularly checked and routine maintenance is done on
              all vehicles. We provide all user friendly and safety facilities
              like Power Windows, Power Steering, Seat Covers, ABS, Air Bags.
            </p>
            <div className="flex justify-center">
              <button className="inline-flex mt-3 text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">
                Learn more
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Service Section Here */}
      <section className="text-grey-500 body-font">
        <div className="container px-5 py-5 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h2 className="text-xs text-blue-600 tracking-widest font-medium title-font mb-1">
              SERVICES
            </h2>
            <h1 className="sm:text-3xl text-2xl font-medium title-font text-blue-950">
              WHAT WE OFFER
            </h1>
          </div>
          <div className="flex flex-wrap m-4">
            <div className="p-4 md:w-1/3 hover:shadow-2xl  ">
              <div className="flex rounded-lg h-full p-8 flex-col">
                <div className="flex items-center mb-3">
                  <div className="w-8 h-8 mr-3 flex flex-col items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
                    <GoLocation />
                  </div>
                  <h2 className="text-blue-950 text-lg title-font font-medium">
                    Pickup and drop anywhere within the city
                  </h2>
                </div>
                <div className="flex-grow">
                  <p className="leading-relaxed text-base  ">
                    Choose your pickup & drop location from within the city.
                  </p>
                  <a className="mt-3 text-blue-500 inline-flex items-center cursor-pointer">
                    Learn More
                  </a>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3 hover:shadow-2xl  ">
              <div className="flex rounded-lg h-full  p-8 flex-col">
                <div className="flex items-center mb-3">
                  <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full font-extrabold bg-blue-500 text-white flex-shrink-0">
                    <BsHandIndexThumb />
                  </div>
                  <h2 className="text-blue-950 text-lg title-font font-medium">
                    Choose vehicle of your choice
                  </h2>
                </div>
                <div className="flex-grow">
                  <p className="leading-relaxed text-base">
                    Get quotes for vehicles which can carry from 20 kgs to 2000
                    kgs and book instantly without any waiting.
                  </p>
                  <a className="mt-3 text-blue-500 inline-flex items-center cursor-pointer">
                    Learn More
                  </a>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3 hover:shadow-2xl ">
              <div className="flex rounded-lg h-full  p-8 flex-col">
                <div className="flex items-center mb-3">
                  <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full font-extrabold bg-blue-500 text-white flex-shrink-0">
                    <AiOutlineSafety />
                  </div>
                  <h2 className="text-blue-950 text-lg title-font font-medium">
                    Safe and Reliable Trucks
                  </h2>
                </div>
                <div className="flex-grow">
                  <p className="leading-relaxed text-base">
                    Superior safety ensured with our team of verified & trained
                    partners.
                  </p>
                  <a className="mt-3 text-blue-500 inline-flex items-center cursor-pointer">
                    Learn More
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Slider Section Here */}
      <section className="mt-8">
        <div className="items-center justify-center">
          <Slider vehicles={vehicles} />
        </div>
      </section>
      {/* Testimonial Section Here */}
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4">
            <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/302x302"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  HOLDEN CAULFIELD
                </h2>
                <p className="text-gray-500">Senior Product Designer</p>
              </div>
            </div>
            <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/300x300"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  ALPER KAMU
                </h2>
                <p className="text-gray-500">UI Develeoper</p>
              </div>
            </div>
            <div className="lg:w-1/3 lg:mb-0 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/305x305"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  HENRY LETHAM
                </h2>
                <p className="text-gray-500">CTO</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI);
  }
  let vehicles = await Vehicles.find();

  return { props: { vehicles: JSON.parse(JSON.stringify(vehicles)) } };
}
